// INCOME
export const SHOW_INCOME_DETAIL = 'SHOW_INCOME_DETAIL'
export const INSERT_NEW_DATES = 'INSERT_NEW_DATES'
export const CALCULATE_WORKED_DAYS = 'CALCULATE_WORKED_DAYS'
export const UPDATE_NEW_JOB_DATA = 'UPDATE_NEW_JOB_DATA'
