// INCOME
export const SHOW_INCOME_DETAIL = 'SHOW_INCOME_DETAIL'
export const INSERT_NEW_DATES = 'INSERT_NEW_DATES'
export const CALCULATE_WORKED_DAYS = 'CALCULATE_WORKED_DAYS'
export const UPDATE_NEW_JOB_DATA = 'UPDATE_NEW_JOB_DATA'
export const UPDATE_INCOME_SOURCES = 'UPDATE_INCOME_SOURCES'
export const UPDATE_INCOME_OUT_OF_TAXES = 'UPDATE_INCOME_OUT_OF_TAXES'
export const UPDATE_TOTAL_INCOME = 'UPDATE_TOTAL_INCOME'
export const UPDATE_LAYOFFS_LAST_YEAR = 'UPDATE_LAYOFFS_LAST_YEAR'
export const EMPTY_LAYOFF_INPUT = 'EMPTY_LAYOFF_INPUT'

// HOME
export const HAS_TO_DECLARE = 'HAS_TO_DECLARE'
export const SHOW_SUMMARY = 'SHOW_SUMMARY'
export const HIDE_SUMMARY = 'HIDE_SUMMARY'
export const SHOW_DEDUCTIONS = 'SHOW_DEDUCTIONS'
export const CHANGE_VIEW = 'CHANGE_VIEW'

// DEDUCTIONS
export const UPDATE_TOTAL_LAYOFFS_VALUE = 'UPDATE_TOTAL_LAYOFFS_VALUE'
export const UPDATE_TOTAL_DEDUCTIONS = 'UPDATE_TOTAL_DEDUCTIONS'
export const UPDATE_DEPENDANTS_DEDUCTION = 'UPDATE_DEPENDANTS_DEDUCTION'
export const UPDATE_DEPENDANTS_VALUE = 'UPDATE_DEPENDANTS_VALUE'
export const UPDATE_DEDUCTION_VALUE = 'UPDATE_DEDUCTION_VALUE'
