name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Muchisimas gracias por contribuir al proyecto, es el primer issue que resuelves'' first issue'
        pr-message: 'Muchisimas gracias por este primer pr, esta app estará lista mucho más rápido'' first pr'
